name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run debug tests
        run: cargo test --verbose

  test-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run release tests
        run: cargo test --release --verbose

  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build doc
        run: cargo doc --verbose
      - name: Deploy doc
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: docs
          FOLDER: target/doc
          CLEAN: true
